### PR TITLE
docs: specify that FCM integration methods must be async

### PR DESCRIPTION
**Pull request by mikehardy**
Causes problems noticed here if not async: https://github.com/notifee/react-native-notifee/issues/14#issuecomment-655024132

### CODE REVIEW

**Comment by mikehardy** [comment]
@Ehesp / @Salakar of interest - notifee problem discovered + solution provided => doc update

**Review by Salakar — APPROVED** [review]
Nice, thanks @mikehardy - I tweaked it slightly 😅

**Comment by mikehardy** [comment]
Yeah - I struggled with it honestly. In the type def for messaging in react-native-firebase repo they are actually not coherent! One of them (onMessage) makes no mention of needing a promise return or being async, but setBackgroundMessageHandler does. Not sure how to fix? The example is clear so perhaps just altering the typedef?

https://github.com/invertase/react-native-firebase/blob/f0959f2054d46578da7769d217cf02f793412a41/packages/messaging/lib/index.d.ts#L621-L647

**Comment by Salakar** [comment]
Have added it to this weeks planner to check out the types, so it should get looked at hopefully by someone 👍

**Pull request merged**
